<a href="https://colab.research.google.com/github/imamahasane/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print("Imam Ahasan _ 3 March 2024")

Imam Ahasan _ 3 March 2024


In [3]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Creating Tensors

In [5]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
scalar.item()

7

In [8]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
matrix.ndim

2

In [13]:
matrix[0]

tensor([7, 8])

In [14]:
matrix[1]

tensor([ 9, 10])

In [15]:
matrix.shape

torch.Size([2, 2])

In [16]:
tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [17]:
tensor.ndim

3

In [18]:
tensor.shape

torch.Size([1, 3, 3])

In [19]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

# Random Tensors

In [20]:
# Create a random tensor of size ()
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5873, 0.9936, 0.7911, 0.0166],
        [0.7306, 0.8827, 0.0136, 0.8990],
        [0.0583, 0.3488, 0.3975, 0.3133]])

In [21]:
random_tensor = torch.rand(9, 5)
random_tensor

tensor([[0.0872, 0.8599, 0.9725, 0.5673, 0.4246],
        [0.0761, 0.3097, 0.0154, 0.3844, 0.0164],
        [0.9011, 0.8627, 0.5278, 0.6405, 0.7228],
        [0.4941, 0.9507, 0.6340, 0.0351, 0.3673],
        [0.5908, 0.5394, 0.5660, 0.7836, 0.6631],
        [0.2328, 0.3052, 0.3232, 0.0078, 0.4727],
        [0.2138, 0.4691, 0.9456, 0.1660, 0.5549],
        [0.6906, 0.2345, 0.7179, 0.2236, 0.6572],
        [0.1667, 0.0687, 0.2558, 0.1230, 0.6720]])

In [22]:
random_tensor.ndim

2

In [23]:
random_tensor = torch.rand(1, 9, 5)
random_tensor

tensor([[[0.4600, 0.9497, 0.2505, 0.5406, 0.1830],
         [0.2652, 0.2443, 0.8145, 0.4416, 0.2607],
         [0.7842, 0.2649, 0.9991, 0.2343, 0.7613],
         [0.9577, 0.2365, 0.1999, 0.7077, 0.4423],
         [0.0351, 0.7148, 0.3911, 0.4659, 0.6377],
         [0.4558, 0.8744, 0.5476, 0.4434, 0.6602],
         [0.1486, 0.5640, 0.7403, 0.8994, 0.4736],
         [0.9850, 0.1768, 0.1087, 0.9174, 0.4709],
         [0.4126, 0.3636, 0.6599, 0.5111, 0.6855]]])

In [24]:
random_tensor.ndim

3

In [25]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [26]:
torch.rand(3, 3)

tensor([[5.3129e-01, 5.8554e-01, 8.0916e-01],
        [4.0855e-01, 4.6992e-04, 5.9474e-01],
        [9.7171e-01, 8.9549e-01, 4.9943e-02]])

In [27]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

## Creating a range of tensors and tensors-like

In [28]:
# use torch.range() and get deprecated message, use to
one_to_ten = torch.arange(start= 1, end= 11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
# creating tensors like
ten_zeros = torch.zeros_like(input= one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatypes

In [30]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype= None)
float_32_tensor

tensor([3., 6., 9.])

In [31]:
float_32_tensor.dtype

torch.float32

In [32]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype= None,   # what datatype is the tensor (e.g. float32, float16)
                               device= None,    #what device is your tensor on
                               requires_grad= False)    #whether or not to track gradients with this tensor oparetion
float_32_tensor

tensor([3., 6., 9.])

In [33]:
float_32_tensor.dtype

torch.float32

In [34]:
# Float 16 tensor
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype= torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [35]:
float_16_tensor.dtype

torch.float16

In [36]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [37]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [38]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [39]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

# Getting information from tensors

In [40]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.9858, 0.1475, 0.8551, 0.9726],
        [0.8120, 0.2177, 0.2811, 0.8296],
        [0.4897, 0.0594, 0.9379, 0.0490]])

In [41]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9858, 0.1475, 0.8551, 0.9726],
        [0.8120, 0.2177, 0.2811, 0.8296],
        [0.4897, 0.0594, 0.9379, 0.0490]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


# Manipulation Tensors (tensor operations)

In [42]:
# creat a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [43]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [44]:
tensor

tensor([1, 2, 3])

In [45]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [46]:
# try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [47]:
torch.add(tensor, 10)

tensor([11, 12, 13])

## Matrix Multiplication

In [48]:
# Element wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [49]:
print(tensor, '*', tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])


In [50]:
print(f"Equals: {tensor * tensor}")

Equals: tensor([1, 4, 9])


In [51]:
# Matrix Multiplications
torch.matmul(tensor, tensor)

tensor(14)

In [52]:
tensor

tensor([1, 2, 3])

In [53]:
# Matrix Multiplication by hand
1 * 1 + 2 * 2 + 3 * 3

14

In [54]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.14 ms, sys: 0 ns, total: 1.14 ms
Wall time: 6.03 ms


In [55]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 69 µs, sys: 10 µs, total: 79 µs
Wall time: 85.1 µs


tensor(14)

## One of the most common errors in deep learning: shape errors

In [56]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

In [57]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [58]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [59]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [60]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [61]:
# creat a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [62]:
# Find the min
torch.min(x)

tensor(0)

In [63]:
# Find the max
torch.max(x)

tensor(90)

In [64]:
torch.mean(x.float())

tensor(45.)

In [65]:
torch.sum(x)

tensor(450)

## Finding the positional min and max

In [66]:
x.argmin()

tensor(0)

In [67]:
x[0]

tensor(0)

In [68]:
x.argmax()

tensor(9)

In [69]:
x[9]

tensor(90)

## Reshaping, Stacking, Squeezing and unsqueeezing tensors

In [70]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [71]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [72]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [73]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [74]:
x_stacked = torch.stack([x, x, x, x], dim= 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [75]:
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [76]:
x_reshaped.shape

torch.Size([1, 9])

In [77]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [78]:
x_reshaped.squeeze().shape

torch.Size([9])

# Selecting data (indexing)

In [79]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [80]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [81]:
x[0, 0]

tensor([1, 2, 3])

In [82]:
x[0, 0, 0]

tensor(1)

In [83]:
x[0, 1, 1]

tensor(5)

In [84]:
x[0, 1, ]

tensor([4, 5, 6])

In [85]:
x[:, 0]

tensor([[1, 2, 3]])

In [86]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [87]:
x[:, 1, 1]

tensor([5])

In [88]:
x[0, 0, :]

tensor([1, 2, 3])

# PyTorch tensors & NumPy

In [89]:
import torch
import numpy as np

In [90]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [91]:
array.dtype

dtype('float64')

In [92]:
tensor.dtype

torch.float64

In [94]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [95]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [97]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [98]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility

In [99]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7576, 0.3845, 0.2296, 0.7564],
        [0.6349, 0.6911, 0.9153, 0.3285],
        [0.1479, 0.3672, 0.4646, 0.4904]])
tensor([[0.5231, 0.5501, 0.2717, 0.4867],
        [0.0747, 0.8009, 0.9860, 0.1421],
        [0.6516, 0.3336, 0.4782, 0.2586]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [100]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
