<a href="https://colab.research.google.com/github/imamahasane/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [176]:
print("Imam Ahasan _ 3 March 2024")

Imam Ahasan _ 3 March 2024


In [177]:
!nvidia-smi

Thu Mar 14 02:50:10 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [178]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Creating Tensors

In [179]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [180]:
scalar.ndim

0

In [181]:
scalar.item()

7

In [182]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [183]:
vector.ndim

1

In [184]:
vector.shape

torch.Size([2])

In [185]:
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [186]:
matrix.ndim

2

In [187]:
matrix[0]

tensor([7, 8])

In [188]:
matrix[1]

tensor([ 9, 10])

In [189]:
matrix.shape

torch.Size([2, 2])

In [190]:
tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [191]:
tensor.ndim

3

In [192]:
tensor.shape

torch.Size([1, 3, 3])

In [193]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

# Random Tensors

In [194]:
# Create a random tensor of size ()
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7192, 0.5586, 0.8822, 0.6234],
        [0.0943, 0.8086, 0.6160, 0.9433],
        [0.2643, 0.6844, 0.0799, 0.3789]])

In [195]:
random_tensor = torch.rand(9, 5)
random_tensor

tensor([[0.3458, 0.8550, 0.2556, 0.2709, 0.1402],
        [0.1365, 0.6589, 0.7503, 0.2132, 0.0022],
        [0.4167, 0.9294, 0.8964, 0.5459, 0.4189],
        [0.7397, 0.3775, 0.2379, 0.1607, 0.8059],
        [0.2157, 0.4710, 0.2050, 0.6420, 0.4714],
        [0.3452, 0.7941, 0.3369, 0.9189, 0.9466],
        [0.7234, 0.0921, 0.1444, 0.0111, 0.7132],
        [0.1111, 0.3753, 0.0871, 0.7105, 0.8087],
        [0.1473, 0.9594, 0.5542, 0.7180, 0.1840]])

In [196]:
random_tensor.ndim

2

In [197]:
random_tensor = torch.rand(1, 9, 5)
random_tensor

tensor([[[0.0115, 0.8921, 0.8279, 0.8707, 0.3321],
         [0.5419, 0.3186, 0.6337, 0.2433, 0.5948],
         [0.9466, 0.6900, 0.3431, 0.6848, 0.4119],
         [0.7442, 0.6838, 0.8932, 0.5000, 0.2715],
         [0.3799, 0.5914, 0.2453, 0.0201, 0.1692],
         [0.8758, 0.0089, 0.8293, 0.4447, 0.8637],
         [0.8912, 0.2155, 0.6605, 0.6525, 0.0940],
         [0.5363, 0.4794, 0.4046, 0.9428, 0.8512],
         [0.4004, 0.0827, 0.5778, 0.8499, 0.7405]]])

In [198]:
random_tensor.ndim

3

In [199]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [200]:
torch.rand(3, 3)

tensor([[0.8265, 0.1241, 0.1029],
        [0.5277, 0.8821, 0.7507],
        [0.8752, 0.1361, 0.9450]])

In [201]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

## Creating a range of tensors and tensors-like

In [202]:
# use torch.range() and get deprecated message, use to
one_to_ten = torch.arange(start= 1, end= 11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [203]:
# creating tensors like
ten_zeros = torch.zeros_like(input= one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatypes

In [204]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype= None)
float_32_tensor

tensor([3., 6., 9.])

In [205]:
float_32_tensor.dtype

torch.float32

In [206]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype= None,   # what datatype is the tensor (e.g. float32, float16)
                               device= None,    #what device is your tensor on
                               requires_grad= False)    #whether or not to track gradients with this tensor oparetion
float_32_tensor

tensor([3., 6., 9.])

In [207]:
float_32_tensor.dtype

torch.float32

In [208]:
# Float 16 tensor
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype= torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [209]:
float_16_tensor.dtype

torch.float16

In [210]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [211]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [212]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [213]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

# Getting information from tensors

In [214]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.2838, 0.9250, 0.2610, 0.7249],
        [0.7197, 0.6291, 0.5539, 0.3591],
        [0.7795, 0.2036, 0.8097, 0.6838]])

In [215]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.2838, 0.9250, 0.2610, 0.7249],
        [0.7197, 0.6291, 0.5539, 0.3591],
        [0.7795, 0.2036, 0.8097, 0.6838]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


# Manipulation Tensors (tensor operations)

In [216]:
# creat a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [217]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [218]:
tensor

tensor([1, 2, 3])

In [219]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [220]:
# try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [221]:
torch.add(tensor, 10)

tensor([11, 12, 13])

## Matrix Multiplication

In [222]:
# Element wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [223]:
print(tensor, '*', tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])


In [224]:
print(f"Equals: {tensor * tensor}")

Equals: tensor([1, 4, 9])


In [225]:
# Matrix Multiplications
torch.matmul(tensor, tensor)

tensor(14)