<a href="https://colab.research.google.com/github/imamahasane/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Imam Ahasan _ 3 March 2024")

Imam Ahasan _ 3 March 2024


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Creating Tensors

In [4]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
matrix.ndim

2

In [12]:
matrix[0]

tensor([7, 8])

In [13]:
matrix[1]

tensor([ 9, 10])

In [14]:
matrix.shape

torch.Size([2, 2])

In [15]:
tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
tensor.ndim

3

In [17]:
tensor.shape

torch.Size([1, 3, 3])

In [18]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

# Random Tensors

In [19]:
# Create a random tensor of size ()
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2663, 0.0780, 0.5847, 0.6411],
        [0.8589, 0.2452, 0.7291, 0.1794],
        [0.8174, 0.5756, 0.9225, 0.4240]])

In [20]:
random_tensor = torch.rand(9, 5)
random_tensor

tensor([[0.8568, 0.2551, 0.2782, 0.4961, 0.5271],
        [0.8158, 0.1398, 0.1565, 0.5097, 0.4127],
        [0.2290, 0.3821, 0.1999, 0.8839, 0.8233],
        [0.2833, 0.8018, 0.2635, 0.2774, 0.9950],
        [0.1208, 0.9537, 0.9286, 0.2764, 0.5471],
        [0.9051, 0.4875, 0.0808, 0.3731, 0.2169],
        [0.3374, 0.6056, 0.1484, 0.5719, 0.9129],
        [0.7635, 0.2711, 0.7849, 0.2830, 0.8381],
        [0.7886, 0.6330, 0.7807, 0.3992, 0.9032]])

In [21]:
random_tensor.ndim

2

In [22]:
random_tensor = torch.rand(1, 9, 5)
random_tensor

tensor([[[0.4473, 0.9669, 0.4048, 0.4190, 0.6011],
         [0.6955, 0.5469, 0.2028, 0.2069, 0.5418],
         [0.8354, 0.5774, 0.9976, 0.7636, 0.3901],
         [0.8435, 0.1209, 0.8989, 0.5612, 0.9233],
         [0.9413, 0.5342, 0.4694, 0.5838, 0.1928],
         [0.8670, 0.5364, 0.3364, 0.5977, 0.1587],
         [0.2919, 0.4791, 0.1068, 0.2864, 0.8796],
         [0.6354, 0.5787, 0.5915, 0.0080, 0.5173],
         [0.8861, 0.0087, 0.9577, 0.9812, 0.5342]]])

In [23]:
random_tensor.ndim

3

In [24]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [25]:
torch.rand(3, 3)

tensor([[0.4102, 0.0745, 0.6349],
        [0.3789, 0.2997, 0.1705],
        [0.1556, 0.8463, 0.5012]])

In [26]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

## Creating a range of tensors and tensors-like

In [27]:
# use torch.range() and get deprecated message, use to
one_to_ten = torch.arange(start= 1, end= 11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
# creating tensors like
ten_zeros = torch.zeros_like(input= one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatypes

In [29]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype= None)
float_32_tensor

tensor([3., 6., 9.])

In [30]:
float_32_tensor.dtype

torch.float32

In [31]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype= None,   # what datatype is the tensor (e.g. float32, float16)
                               device= None,    #what device is your tensor on
                               requires_grad= False)    #whether or not to track gradients with this tensor oparetion
float_32_tensor

tensor([3., 6., 9.])

In [32]:
float_32_tensor.dtype

torch.float32

In [33]:
# Float 16 tensor
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype= torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [34]:
float_16_tensor.dtype

torch.float16

In [35]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [36]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [37]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [38]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

# Getting information from tensors

In [39]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.9185, 0.9950, 0.1884, 0.4134],
        [0.2926, 0.6213, 0.2167, 0.6116],
        [0.1297, 0.9097, 0.8194, 0.5911]])

In [40]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9185, 0.9950, 0.1884, 0.4134],
        [0.2926, 0.6213, 0.2167, 0.6116],
        [0.1297, 0.9097, 0.8194, 0.5911]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


# Manipulation Tensors (tensor operations)

In [41]:
# creat a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [42]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [43]:
tensor

tensor([1, 2, 3])

In [44]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [45]:
# try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [46]:
torch.add(tensor, 10)

tensor([11, 12, 13])

## Matrix Multiplication

In [47]:
# Element wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [48]:
print(tensor, '*', tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])


In [49]:
print(f"Equals: {tensor * tensor}")

Equals: tensor([1, 4, 9])


In [50]:
# Matrix Multiplications
torch.matmul(tensor, tensor)

tensor(14)

In [51]:
tensor

tensor([1, 2, 3])

In [52]:
# Matrix Multiplication by hand
1 * 1 + 2 * 2 + 3 * 3

14

In [53]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 3 ms, sys: 0 ns, total: 3 ms
Wall time: 4.32 ms


In [54]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 891 µs, sys: 0 ns, total: 891 µs
Wall time: 1.09 ms


tensor(14)

## One of the most common errors in deep learning: shape errors

In [55]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

In [56]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [57]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [58]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [59]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [60]:
# creat a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [61]:
# Find the min
torch.min(x)

tensor(0)

In [62]:
# Find the max
torch.max(x)

tensor(90)

In [63]:
torch.mean(x.float())

tensor(45.)

In [64]:
torch.sum(x)

tensor(450)

## Finding the positional min and max

In [65]:
x.argmin()

tensor(0)

In [66]:
x[0]

tensor(0)

In [67]:
x.argmax()

tensor(9)

In [68]:
x[9]

tensor(90)

## Reshaping, Stacking, Squeezing and unsqueeezing tensors

In [69]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [70]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [71]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [72]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [73]:
x_stacked = torch.stack([x, x, x, x], dim= 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [74]:
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [75]:
x_reshaped.shape

torch.Size([1, 9])

In [76]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [77]:
x_reshaped.squeeze().shape

torch.Size([9])

# Selecting data (indexing)

In [78]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [79]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [80]:
x[0, 0]

tensor([1, 2, 3])

In [81]:
x[0, 0, 0]

tensor(1)

In [82]:
x[0, 1, 1]

tensor(5)

In [83]:
x[0, 1, ]

tensor([4, 5, 6])

In [84]:
x[:, 0]

tensor([[1, 2, 3]])

In [85]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [86]:
x[:, 1, 1]

tensor([5])

In [87]:
x[0, 0, :]

tensor([1, 2, 3])

# PyTorch tensors & NumPy

In [88]:
import torch
import numpy as np

In [89]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [90]:
array.dtype

dtype('float64')

In [91]:
tensor.dtype

torch.float64

In [92]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [93]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [94]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [95]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility

In [96]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.5957, 0.0433, 0.8032, 0.9669],
        [0.3150, 0.8364, 0.9080, 0.1469],
        [0.4831, 0.6007, 0.4359, 0.9010]])
tensor([[0.3391, 0.0598, 0.2926, 0.1684],
        [0.1191, 0.6792, 0.2072, 0.0498],
        [0.3219, 0.5135, 0.9480, 0.7104]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [97]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [99]:
# Check for GPU access with PyTorch
torch.cuda.is_available()

False

In [100]:
# setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [101]:
# Count number of device
torch.cuda.device_count()

0