<a href="https://colab.research.google.com/github/imamahasane/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print("Imam Ahasan _ 3 March 2024")

Imam Ahasan _ 3 March 2024


In [3]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Creating Tensors

In [5]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
scalar.item()

7

In [8]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
matrix.ndim

2

In [13]:
matrix[0]

tensor([7, 8])

In [14]:
matrix[1]

tensor([ 9, 10])

In [15]:
matrix.shape

torch.Size([2, 2])

In [16]:
tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [17]:
tensor.ndim

3

In [18]:
tensor.shape

torch.Size([1, 3, 3])

In [19]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

# Random Tensors

In [20]:
# Create a random tensor of size ()
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0348, 0.1449, 0.9903, 0.2939],
        [0.5396, 0.7085, 0.4778, 0.5823],
        [0.5209, 0.0825, 0.6874, 0.2971]])

In [21]:
random_tensor = torch.rand(9, 5)
random_tensor

tensor([[0.4848, 0.2802, 0.5680, 0.4931, 0.4279],
        [0.4741, 0.2346, 0.2996, 0.1743, 0.9018],
        [0.5371, 0.2100, 0.7394, 0.9121, 0.7589],
        [0.6111, 0.1353, 0.3760, 0.0632, 0.5072],
        [0.9734, 0.6855, 0.3478, 0.1499, 0.9969],
        [0.9960, 0.6701, 0.0659, 0.5544, 0.8859],
        [0.4083, 0.3912, 0.5955, 0.5211, 0.0035],
        [0.0650, 0.0129, 0.3407, 0.1053, 0.4324],
        [0.6126, 0.2008, 0.3118, 0.7427, 0.4450]])

In [22]:
random_tensor.ndim

2

In [23]:
random_tensor = torch.rand(1, 9, 5)
random_tensor

tensor([[[0.8883, 0.2790, 0.7883, 0.5297, 0.0736],
         [0.5560, 0.0442, 0.5121, 0.8667, 0.4808],
         [0.5529, 0.7856, 0.6938, 0.5315, 0.4187],
         [0.2499, 0.2879, 0.8162, 0.7191, 0.3991],
         [0.7093, 0.8953, 0.5704, 0.1277, 0.3303],
         [0.2964, 0.5159, 0.9380, 0.8139, 0.5461],
         [0.2359, 0.6606, 0.7067, 0.3004, 0.9572],
         [0.4813, 0.7663, 0.3467, 0.6784, 0.7200],
         [0.9010, 0.9349, 0.3339, 0.0218, 0.2570]]])

In [24]:
random_tensor.ndim

3

In [25]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [26]:
torch.rand(3, 3)

tensor([[0.7351, 0.2271, 0.3618],
        [0.8066, 0.6824, 0.4537],
        [0.8770, 0.7306, 0.9619]])

In [27]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

## Creating a range of tensors and tensors-like

In [28]:
# use torch.range() and get deprecated message, use to
one_to_ten = torch.arange(start= 1, end= 11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
# creating tensors like
ten_zeros = torch.zeros_like(input= one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatypes

In [30]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype= None)
float_32_tensor

tensor([3., 6., 9.])

In [31]:
float_32_tensor.dtype

torch.float32

In [32]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype= None,   # what datatype is the tensor (e.g. float32, float16)
                               device= None,    #what device is your tensor on
                               requires_grad= False)    #whether or not to track gradients with this tensor oparetion
float_32_tensor

tensor([3., 6., 9.])

In [33]:
float_32_tensor.dtype

torch.float32

In [34]:
# Float 16 tensor
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype= torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [35]:
float_16_tensor.dtype

torch.float16

In [36]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [37]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [38]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [39]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

# Getting information from tensors

In [40]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4287, 0.2807, 0.4752, 0.7529],
        [0.4079, 0.8408, 0.5010, 0.5597],
        [0.3627, 0.1723, 0.5852, 0.4795]])

In [41]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4287, 0.2807, 0.4752, 0.7529],
        [0.4079, 0.8408, 0.5010, 0.5597],
        [0.3627, 0.1723, 0.5852, 0.4795]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


# Manipulation Tensors (tensor operations)

In [42]:
# creat a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [43]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [44]:
tensor

tensor([1, 2, 3])

In [45]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [46]:
# try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [47]:
torch.add(tensor, 10)

tensor([11, 12, 13])

## Matrix Multiplication

In [48]:
# Element wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [49]:
print(tensor, '*', tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])


In [50]:
print(f"Equals: {tensor * tensor}")

Equals: tensor([1, 4, 9])


In [51]:
# Matrix Multiplications
torch.matmul(tensor, tensor)

tensor(14)

In [52]:
tensor

tensor([1, 2, 3])

In [53]:
# Matrix Multiplication by hand
1 * 1 + 2 * 2 + 3 * 3

14

In [54]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.41 ms, sys: 897 µs, total: 2.31 ms
Wall time: 4.06 ms


In [55]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 61 µs, sys: 11 µs, total: 72 µs
Wall time: 76.3 µs


tensor(14)

## One of the most common errors in deep learning: shape errors

In [58]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

In [59]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [67]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [69]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [70]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [71]:
# creat a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [72]:
# Find the min
torch.min(x)

tensor(0)

In [73]:
# Find the max
torch.max(x)

tensor(90)

In [75]:
torch.mean(x.float())

tensor(45.)

In [76]:
torch.sum(x)

tensor(450)

## Finding the positional min and max

In [77]:
x.argmin()

tensor(0)

In [78]:
x[0]

tensor(0)

In [79]:
x.argmax()

tensor(9)

In [80]:
x[9]

tensor(90)

## Reshaping, Stacking, Squeezing and unsqueeezing tensors

In [82]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [83]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [84]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [85]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [86]:
x_stacked = torch.stack([x, x, x, x], dim= 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])